# Generated by Django 4.1.2 on 2022-11-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('designation', models.CharField(blank=True, max_length=10, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('salaryrange', models.IntegerField(blank=True, null=True)),
                ('deptid', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'EMPLOYEES',
                'managed': True,
            },
        ),
    ]
