# Generated by Django 4.1.2 on 2022-11-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('phoneno', models.IntegerField(blank=True, null=True)),
                ('streetname', models.CharField(blank=True, max_length=10, null=True)),
                ('areaname', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PATIENT',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
