# Generated by Django 4.1.3 on 2022-11-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('deptname', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
    ]
